#!/usr/bin/env bash
# Prerequisites for the monitoring agent (docs/PIANO-AGENTE.md, phase 1).
# Idempotent: it can be run again, existing passwords and tokens are kept.
#
#   ./setup-agent-prereqs.sh                  Linux user + MariaDB read-only user
#   ./setup-agent-prereqs.sh --install-claude also installs Claude Code for the agent user
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
AGENT_USER="raspi-agent"
AGENT_HOME="/home/${AGENT_USER}"
AGENT_CONFIG_DIR="${AGENT_HOME}/.config/raspi-agent"
AGENT_ENV="${AGENT_CONFIG_DIR}/agent.env"
RO_USER="agent_ro"
INSTALL_CLAUDE=false

for arg in "$@"; do
	case "${arg}" in
		--install-claude) INSTALL_CLAUDE=true ;;
		*) echo "Unknown argument: ${arg}"; exit 1 ;;
	esac
done

# Reads KEY from a dotenv file (last occurrence wins, surrounding quotes removed)
env_get() {
	local file="$1" key="$2" fallback="${3:-}"
	local value
	value="$(sudo grep -E "^${key}=" "${file}" 2>/dev/null | tail -n 1 | cut -d= -f2- | sed -e 's/^"//' -e 's/"$//' || true)"
	echo "${value:-${fallback}}"
}

cd "${PROJECT_DIR}"

if [[ ! -f ".env" ]]; then
	echo "Error: .env not found in ${PROJECT_DIR}."
	exit 1
fi

MARIADB_HOST="$(env_get .env MARIADB_HOST localhost)"
MARIADB_PORT="$(env_get .env MARIADB_PORT 3306)"
MARIADB_DATABASE="$(env_get .env MARIADB_DATABASE sensor_data)"
MQTT_BROKER="$(env_get .env MQTT_BROKER mqtt://localhost:1883)"
MQTT_USERNAME="$(env_get .env MQTT_USERNAME)"
MQTT_PASSWORD="$(env_get .env MQTT_PASSWORD)"

if [[ "${MARIADB_HOST}" != "localhost" && "${MARIADB_HOST}" != "127.0.0.1" ]]; then
	echo "Error: this script creates the MariaDB user through the local socket (sudo mysql)."
	echo "MARIADB_HOST is ${MARIADB_HOST}: create the read-only user by hand."
	exit 1
fi

ARCH="$(uname -m)"
if [[ "${ARCH}" != "aarch64" ]]; then
	echo "Warning: architecture ${ARCH}. Claude Code needs a 64-bit OS (aarch64)."
fi

# ─── 1. Linux user for the agent ───────────────────────────────────────────
if id "${AGENT_USER}" &>/dev/null; then
	echo "[=] Linux user ${AGENT_USER} already exists"
else
	echo "[+] Creating Linux user ${AGENT_USER} (no sudo, no login shell)"
	sudo useradd --system --create-home --home-dir "${AGENT_HOME}" --shell /usr/sbin/nologin "${AGENT_USER}"
fi

if id -nG "${AGENT_USER}" | grep -qwE 'sudo|adm|wheel'; then
	echo "Error: ${AGENT_USER} belongs to an administrative group. Remove it before continuing."
	exit 1
fi

sudo install -d -m 700 -o "${AGENT_USER}" -g "${AGENT_USER}" \
	"${AGENT_HOME}/.config" "${AGENT_CONFIG_DIR}" "${AGENT_HOME}/workspace" "${AGENT_HOME}/notes"

# ─── 2. MariaDB read-only user ─────────────────────────────────────────────
RO_PASSWORD="$(env_get "${AGENT_ENV}" MARIADB_RO_PASSWORD)"
if [[ -z "${RO_PASSWORD}" ]]; then
	RO_PASSWORD="$(openssl rand -hex 24)"
	echo "[+] Generated a new password for ${RO_USER}"
fi

echo "[+] Creating/updating MariaDB user ${RO_USER} (SELECT only on ${MARIADB_DATABASE})"
sudo mysql <<SQL
CREATE USER IF NOT EXISTS '${RO_USER}'@'localhost' IDENTIFIED BY '${RO_PASSWORD}';
ALTER USER '${RO_USER}'@'localhost' IDENTIFIED BY '${RO_PASSWORD}';
GRANT SELECT ON \`${MARIADB_DATABASE}\`.* TO '${RO_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL

# Resource limits: a heavy query from the agent must not slow down the services
if ! sudo mysql -e "ALTER USER '${RO_USER}'@'localhost' WITH MAX_USER_CONNECTIONS 3 MAX_STATEMENT_TIME 10;"; then
	echo "Warning: could not set resource limits on ${RO_USER} (older MariaDB?)."
fi

# ─── 3. Agent environment file (readable only by the agent user) ───────────
OAUTH_TOKEN="$(env_get "${AGENT_ENV}" CLAUDE_CODE_OAUTH_TOKEN)"

echo "[+] Writing ${AGENT_ENV}"
sudo tee "${AGENT_ENV}" > /dev/null <<EOF
# Generated by setup-agent-prereqs.sh — values are kept when the script runs again.
MARIADB_HOST=${MARIADB_HOST}
MARIADB_PORT=${MARIADB_PORT}
MARIADB_DATABASE=${MARIADB_DATABASE}
MARIADB_RO_USER=${RO_USER}
MARIADB_RO_PASSWORD=${RO_PASSWORD}
MQTT_BROKER=${MQTT_BROKER}
MQTT_USERNAME=${MQTT_USERNAME}
MQTT_PASSWORD=${MQTT_PASSWORD}
# Long-lived token generated with "claude setup-token" (Claude subscription)
CLAUDE_CODE_OAUTH_TOKEN=${OAUTH_TOKEN}
EOF
sudo chown "${AGENT_USER}:${AGENT_USER}" "${AGENT_ENV}"
sudo chmod 600 "${AGENT_ENV}"

# ─── 4. Checks on the read-only user ───────────────────────────────────────
echo "[?] Checking read access..."
MYSQL_PWD="${RO_PASSWORD}" mysql -h 127.0.0.1 -P "${MARIADB_PORT}" -u "${RO_USER}" "${MARIADB_DATABASE}" \
	-e "SELECT COUNT(*) AS tables_visible FROM information_schema.tables WHERE table_schema = DATABASE();"

echo "[?] Checking that writing is refused..."
if MYSQL_PWD="${RO_PASSWORD}" mysql -h 127.0.0.1 -P "${MARIADB_PORT}" -u "${RO_USER}" "${MARIADB_DATABASE}" \
	-e "CREATE TABLE agent_ro_write_test (id INT);" 2>/dev/null; then
	sudo mysql -e "DROP TABLE \`${MARIADB_DATABASE}\`.agent_ro_write_test;"
	echo "Error: ${RO_USER} can write to the database!"
	exit 1
fi
echo "[✓] ${RO_USER} is read-only"

# ─── 5. Claude Code (optional) ─────────────────────────────────────────────
CLAUDE_BIN="${AGENT_HOME}/.local/bin/claude"
if [[ "${INSTALL_CLAUDE}" == true ]]; then
	echo "[+] Installing Claude Code for ${AGENT_USER}..."
	sudo -u "${AGENT_USER}" -H bash -c 'curl -fsSL https://claude.ai/install.sh | bash'
fi

if sudo test -x "${CLAUDE_BIN}"; then
	echo "[✓] Claude Code: $(sudo -u "${AGENT_USER}" -H "${CLAUDE_BIN}" --version)"
else
	echo "[ ] Claude Code not installed yet (run again with --install-claude)"
fi

echo
echo "Done. Next steps:"
if [[ -z "${OAUTH_TOKEN}" ]]; then
	echo "  1. On a PC with a browser: claude setup-token"
	echo "     then paste the token in CLAUDE_CODE_OAUTH_TOKEN= with:"
	echo "       sudo nano ${AGENT_ENV}"
fi
echo "  2. Test the agent login:"
echo "       sudo -u ${AGENT_USER} -H bash -c 'set -a; . ${AGENT_ENV}; cd ~/workspace; ${CLAUDE_BIN} -p \"Rispondi solo OK\" --model haiku'"
